Connecting to api part 1
jbendzala/ecommerce-jakub pull request #13
Opened 2023-02-21 19:25 UTC by jbendzala

2023-02-22 19:51 UTC, cypcz requested changes

2023-02-22 19:51 UTC, cypcz commented on lobis-repo/client/src/apiClient/apiClient.ts
> +export const useGetBusiness = ({ businessId }: { businessId: string }) => {
`useGetAdminBusiness`

2023-02-22 19:51 UTC, cypcz commented on lobis-repo/client/src/apiClient/apiClient.ts
> +export const useGetProducts = ({ businessId }: { businessId: string }) => {
`useGetAdminProducts`

2023-02-22 19:51 UTC, cypcz commented on lobis-repo/client/src/components/Product/ProductCard.tsx
> +          image={data?.images?.[0]}
A co ostatni images? :D

2023-02-22 19:51 UTC, cypcz commented on lobis-repo/client/src/components/Product/ProductCard.tsx
> +export const ProductCard = (data: ProductCardProps) => {
destructure props

2023-02-22 19:51 UTC, cypcz commented on lobis-repo/client/src/components/Product/ProductCard.tsx
> +          image={data?.images?.[0]}
`data` neni optional podle typu nahore

2023-02-22 19:51 UTC, cypcz commented on lobis-repo/client/src/components/ShoppingCart/ShoppingCartDrawer.tsx
> +  const hadleRemove = (product: ProductCardProps) => {
typ parametru funkce by se nemel jmenovat `props`

2023-02-22 19:51 UTC, cypcz commented on lobis-repo/client/src/components/Product/ProductCard.tsx
> +};
```suggestion
export type Props = {
  product: Product
};
```

2023-02-22 19:51 UTC, cypcz commented on lobis-repo/client/src/hooks/useCart.tsx
>      : 'přidat do košíku';
na co tu je toto? :D

2023-02-22 19:51 UTC, cypcz commented on lobis-repo/client/src/routes/BusinessDetail.tsx
> +  const { data } = useGetBusiness({
tady uz si vrat primo `business`, pouzivat dole `data.data` je ugh

2023-02-22 19:51 UTC, cypcz commented on lobis-repo/client/src/routes/Products.tsx
> +  const products: ProductCardProps[] = data?.data;
nemel bys tady pridavat typ, mel by byt automaticky

2023-02-22 19:51 UTC, cypcz commented on lobis-repo/client/src/types/types.ts
> +  data: {
`data` zbytecne, produkt ma rovnou sve properties

2023-02-22 19:51 UTC, cypcz commented on lobis-repo/client/src/types/types.ts
> +  data: {
to same co vyse

2023-02-23 18:21 UTC, jbendzala commented on lobis-repo/client/src/hooks/useCart.tsx
>      : 'přidat do košíku';
kamo stare veci, cekni najnovsi commit :D

2023-02-23 18:24 UTC, jbendzala commented on lobis-repo/client/src/routes/BusinessDetail.tsx
> +  const { data } = useGetBusiness({
good takto, alebo ako si myslel?

2023-02-23 18:26 UTC, jbendzala commented on lobis-repo/client/src/routes/Products.tsx
> +  const products: ProductCardProps[] = data?.data;
nejde mi dat ako response type generikum array do useQuery 🤷

2023-02-27 18:38 UTC, merged