Add business status on BE
jbendzala/ecommerce-jakub pull request #58
Opened 2023-06-07 13:11 UTC by jbendzala

2023-06-07 19:11 UTC, cypcz requested changes

2023-06-07 19:11 UTC, cypcz commented on lobis-repo/server/prisma/schema.prisma
> +  businessStatus  BusinessStatus?
I'd name it just `status` (the enum name can stay as is). It's obvious that it's business status if it's on business entity.

2023-06-07 19:11 UTC, cypcz commented on lobis-repo/server/src/handlers/admin/business/business.ts
> +            businessStatus: 'PENDING',
use the enum here :)

2023-06-07 19:11 UTC, cypcz commented on lobis-repo/server/src/handlers/admin/business/business.ts
> +    const { name, description, images, categories, businessStatus } = req.body
why is the status in the input? user should not be able to change it..

2023-06-07 19:11 UTC, cypcz commented on lobis-repo/server/src/handlers/public/business/business.ts
> +            businessStatus: 'ACTIVE',
use enum

2023-06-08 07:27 UTC, jbendzala commented on lobis-repo/server/prisma/schema.prisma
> +  businessStatus  BusinessStatus?
Good point, renamed

2023-06-08 07:31 UTC, jbendzala commented on lobis-repo/server/src/routes/public/business.ts
> +router.get('/pending', getPendingBusinesses)
This is exactly what I was aiming for. In the future, there will be some "Approver" or "Super admin" or something like that, with access to this  hidden "approving" part of the app. Should I leave it like it is, or change it to query filter?

2023-06-08 07:33 UTC, jbendzala commented on lobis-repo/server/src/handlers/admin/business/business.ts
> +    const { name, description, images, categories, businessStatus } = req.body
In the future, I'd like to change statuses from some hidden "approving" part of the app. Should I create a different endpoint only for status change then?

2023-06-12 07:41 UTC, merged