Password recovery flow
jbendzala/ecommerce-jakub pull request #80
Opened 2023-06-30 12:54 UTC by jbendzala

@cypcz again some BE work here 👁️

2023-06-30 14:08 UTC, cypcz requested changes

2023-06-30 14:08 UTC, cypcz commented on lobis-repo/client/src/customer/context/ChangePasswordContext.tsx
> +const ChangePasswordContext = createContext<{
I don't think context is needed for this at all. Why did you use it?

2023-06-30 14:08 UTC, cypcz commented on lobis-repo/client/src/shared/components/PasswordRecovery/ChangePassword.tsx
> +  const isValidLink = id === passwordContext?.link;
FE shouldn't be evaluating this, anyone can just inspect the code and set this to `true`

2023-06-30 14:08 UTC, cypcz commented on lobis-repo/client/src/shared/components/PasswordRecovery/ChangePassword.tsx
> +  const isNarrow = windowSize.width && windowSize.width < NARROW_SCREEN;
we should have a hook that returns something like `belowLg` or `aboveSm` where `Lg` and `Sm` are generally used browser size thresholds

2023-06-30 14:08 UTC, cypcz commented on lobis-repo/client/src/shared/components/PasswordRecovery/PasswordRecovery.tsx
> +  const link = uuidv4();
why not use JWT? with short expiration, I think it would be ideal candidate for this use case

2023-06-30 14:08 UTC, cypcz commented on lobis-repo/server/src/handlers/passwordRecovery/passwordRecovery.ts
> +        pass: process.env.GMAIL_PASSWORD,
👍

2023-06-30 14:37 UTC, jbendzala commented on lobis-repo/client/src/customer/context/ChangePasswordContext.tsx
> +const ChangePasswordContext = createContext<{
How else would you know the correct link? I pass it there when I create one and then compare it in different component. Would you prefer to have it stored in BE, in some password/link endpoint or smth?

2023-06-30 14:38 UTC, jbendzala commented on lobis-repo/client/src/shared/components/PasswordRecovery/ChangePassword.tsx
> +  const isValidLink = id === passwordContext?.link;
Oh 💩 , so we'll store it on BE?

2023-06-30 14:39 UTC, jbendzala commented on lobis-repo/client/src/shared/components/PasswordRecovery/ChangePassword.tsx
> +  const isNarrow = windowSize.width && windowSize.width < NARROW_SCREEN;
Ok, I was also thinking about smth similar, will do later

2023-06-30 14:39 UTC, jbendzala commented on lobis-repo/client/src/shared/components/PasswordRecovery/PasswordRecovery.tsx
> +  const link = uuidv4();
Good point, will fix

2023-07-02 05:19 UTC, cypcz commented on lobis-repo/client/src/customer/context/ChangePasswordContext.tsx
> +const ChangePasswordContext = createContext<{
Can you explain to me how do you see the whole flow? What is generated where, what is sent where, etc.

2023-07-03 10:49 UTC, merged