Change password api + full flow
jbendzala/ecommerce-jakub pull request #81
Opened 2023-06-30 13:18 UTC by jbendzala

2023-06-30 13:22 UTC, jbendzala commented
Only last commit is relevant

2023-06-30 14:11 UTC, cypcz requested changes

2023-06-30 14:11 UTC, cypcz commented on lobis-repo/client/src/shared/components/PasswordRecovery/ChangePassword.tsx
> +  const { id, email } = useParams<{ id: string; email: string }>();
params can be undefined, we shouldn't just assume that it's there

2023-06-30 14:11 UTC, cypcz commented on lobis-repo/client/src/shared/components/PasswordRecovery/ChangePassword.tsx
> +                localStorage.setItem('token', res.data.token);
I don't think there's a need to use local storage for anything related to forgetting + changing password.

2023-06-30 14:40 UTC, jbendzala commented on lobis-repo/client/src/shared/components/PasswordRecovery/ChangePassword.tsx
> +  const { id, email } = useParams<{ id: string; email: string }>();
Ok, will fix

2023-06-30 14:42 UTC, jbendzala commented on lobis-repo/client/src/shared/components/PasswordRecovery/ChangePassword.tsx
> +                localStorage.setItem('token', res.data.token);
I was aiming for a silent login after password change, should we then change the FE login logic? Or don't do silent login at all and just redirect user to login screen?

2023-07-02 05:22 UTC, cypcz commented on lobis-repo/client/src/shared/components/PasswordRecovery/ChangePassword.tsx
> +                localStorage.setItem('token', res.data.token);
I'd do the redirect. I think it's common practise. And makes the user remember the password better :D

2023-07-03 08:23 UTC, jbendzala commented on lobis-repo/client/src/shared/components/PasswordRecovery/ChangePassword.tsx
> +                localStorage.setItem('token', res.data.token);
All fixed according to our yesterdays call

2023-07-03 08:23 UTC, jbendzala commented on lobis-repo/server/src/handlers/auth/auth.ts
> +    if ((verify as TokenInterface)?.email !== email || !verify) {
@cypcz Is this validation good enough?

2023-07-03 08:33 UTC, cypcz reviewed
Looks good now! I'd also recommend to include a second input for password to make sure user didn't do a typo.

2023-07-03 08:33 UTC, cypcz commented on lobis-repo/client/src/shared/components/PasswordRecovery/ChangePassword.tsx
> +    token ? token : ''
token ?? ''

2023-07-03 08:33 UTC, cypcz commented on lobis-repo/client/src/shared/components/PasswordRecovery/ChangePassword.tsx
> +  const decode: { email: string; iat: number; exp: number } = jwt_decode(
There should also be some error handling if decoding the token fails.

2023-07-03 08:33 UTC, cypcz commented on lobis-repo/client/src/shared/components/PasswordRecovery/ChangePassword.tsx
> +      { email, password, token: String(token) },
why `String()`?

2023-07-03 08:33 UTC, cypcz commented on lobis-repo/client/src/shared/components/PasswordRecovery/ChangePassword.tsx
> +      { email, password, token: String(token) },
No need to send email, it can be taken from the token on the BE.

2023-07-03 08:33 UTC, cypcz commented on lobis-repo/server/src/handlers/auth/auth.ts
> +    const verify = jwt.verify(token, config.secrets.jwt)
`verify` sounds like an action (function). I think naming it something like `verifiedToken` makes more sense.

2023-07-03 08:33 UTC, cypcz commented on lobis-repo/server/src/handlers/auth/auth.ts
> +    if ((verify as TokenInterface)?.email !== email || !verify) {
no need, just verifying the token must succeed.

2023-07-03 08:33 UTC, cypcz commented on lobis-repo/server/src/typings.d.ts
> +export interface TokenInterface {
not very descriptive. it's specific to reset password token but it's defined in the common file.

2023-07-03 08:56 UTC, jbendzala commented on lobis-repo/server/src/typings.d.ts
> +export interface TokenInterface {
removed as it is not used anymore

2023-07-03 09:02 UTC, jbendzala commented on lobis-repo/client/src/shared/components/PasswordRecovery/ChangePassword.tsx
> +  const decode: { email: string; iat: number; exp: number } = jwt_decode(
added condition for rendering "Invalid link" screen

2023-07-03 09:04 UTC, jbendzala commented on lobis-repo/client/src/shared/components/PasswordRecovery/ChangePassword.tsx
> +      { email, password, token: String(token) },
kk, all fixed 🙏

2023-07-03 10:49 UTC, merged